name = "TrixiBottomTopography"
uuid = "86af9953-43df-404b-8eaa-d20d82623a82"
authors = ["maxbertrand1996 <maxbertrand1996@googlemail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.7"